#!/usr/bin/env python3
# -*- encoding:utf-8 -*-
# 回溯
class Solution:
    def permute(self, nums):
        res = []
        def backtracking(nums, tmp):
            if not nums:
                res.append(tmp)
                return
            for i in range(len(nums)):
                backtracking(nums[:i] + nums[i+1:], tmp + [nums[i]])
        backtracking(nums, [])
        return res
